-- ============================================================================
-- Roleta de Filmes — Autenticação, contas e sessões compartilhadas
-- Rode este script inteiro no SQL Editor do Supabase (Project > SQL Editor).
--
-- Não apaga nem altera a tabela `filmes_imdb` existente — ela fica intocada
-- como histórico legado, sem uso pelo código novo.
-- ============================================================================

create extension if not exists pgcrypto;

-- ----------------------------------------------------------------------------
-- 1. profiles — perfil público (nome/apelido) de cada usuário autenticado
-- ----------------------------------------------------------------------------
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- ----------------------------------------------------------------------------
-- 2. sessions — uma sessão compartilhada entre 2 (ou mais, no futuro) usuários
-- ----------------------------------------------------------------------------
create table public.sessions (
  id uuid primary key default gen_random_uuid(),
  name text,
  owner_id uuid not null references public.profiles (id),
  max_members int not null default 2,
  status text not null default 'active' check (status in ('active', 'ended')),
  invite_code text unique,
  invite_code_expires_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.sessions enable row level security;

-- ----------------------------------------------------------------------------
-- 3. session_members — participação (join table sessions <-> profiles)
-- ----------------------------------------------------------------------------
create table public.session_members (
  session_id uuid not null references public.sessions (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  joined_at timestamptz not null default now(),
  primary key (session_id, user_id)
);

-- um usuário só pode estar em UMA sessão ativa por vez
create unique index session_members_one_active_per_user
  on public.session_members (user_id);

alter table public.session_members enable row level security;

-- ----------------------------------------------------------------------------
-- 4. watched_movies — substitui `filmes_imdb` para uso da aplicação
--    session_id NULL  -> registro individual (dono = user_id)
--    session_id != NULL -> registro compartilhado da sessão
-- ----------------------------------------------------------------------------
create table public.watched_movies (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  session_id uuid references public.sessions (id) on delete cascade,
  ranking_imdb integer not null,
  nome_filme text,
  assistido boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index watched_movies_personal_uidx
  on public.watched_movies (user_id, ranking_imdb)
  where session_id is null;

create unique index watched_movies_session_uidx
  on public.watched_movies (session_id, ranking_imdb)
  where session_id is not null;

alter table public.watched_movies enable row level security;

-- ----------------------------------------------------------------------------
-- 5. Função auxiliar (SECURITY DEFINER) — evita recursão de RLS ao checar
--    se o usuário atual participa de uma sessão específica.
-- ----------------------------------------------------------------------------
create or replace function public.is_session_member(p_session_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.session_members
    where session_id = p_session_id and user_id = auth.uid()
  );
$$;

-- ----------------------------------------------------------------------------
-- 6. Trigger — cria a linha em profiles automaticamente no signup
-- ----------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ----------------------------------------------------------------------------
-- 7. RLS policies
-- ----------------------------------------------------------------------------

-- profiles: vejo meu perfil e o de quem divide sessão comigo
create policy "profiles_select" on public.profiles
  for select
  using (
    id = auth.uid()
    or exists (
      select 1 from public.session_members sm
      where sm.user_id = profiles.id
        and public.is_session_member(sm.session_id)
    )
  );

create policy "profiles_insert_own" on public.profiles
  for insert
  with check (id = auth.uid());

create policy "profiles_update_own" on public.profiles
  for update
  using (id = auth.uid());

-- sessions: só membros enxergam a sessão; escrita só via RPCs (abaixo)
create policy "sessions_select_members" on public.sessions
  for select
  using (public.is_session_member(id));

-- session_members: só membros enxergam a lista de membros; escrita só via RPCs
create policy "session_members_select" on public.session_members
  for select
  using (public.is_session_member(session_id));

-- watched_movies: leitura própria (pessoal) ou da sessão; escrita só via RPCs
create policy "watched_movies_select" on public.watched_movies
  for select
  using (
    (session_id is null and user_id = auth.uid())
    or (session_id is not null and public.is_session_member(session_id))
  );

-- ----------------------------------------------------------------------------
-- 8. RPCs — toda escrita sensível passa por aqui (SECURITY DEFINER),
--    nunca recebendo user_id/session_id do client: sempre derivados de
--    auth.uid() e da tabela session_members no servidor.
-- ----------------------------------------------------------------------------

create or replace function public.create_session(p_name text default null)
returns public.sessions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.sessions;
  v_code text;
begin
  if exists (select 1 from public.session_members where user_id = auth.uid()) then
    raise exception 'Você já participa de uma sessão. Saia da sessão atual antes de criar outra.';
  end if;

  v_code := upper(substr(md5(random()::text || clock_timestamp()::text), 1, 6));

  insert into public.sessions (name, owner_id, invite_code, invite_code_expires_at)
  values (p_name, auth.uid(), v_code, now() + interval '7 days')
  returning * into v_session;

  insert into public.session_members (session_id, user_id, role)
  values (v_session.id, auth.uid(), 'owner');

  return v_session;
end;
$$;

create or replace function public.join_session_by_code(p_code text)
returns public.sessions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.sessions;
  v_member_count int;
begin
  if exists (select 1 from public.session_members where user_id = auth.uid()) then
    raise exception 'Você já participa de uma sessão. Saia da sessão atual antes de entrar em outra.';
  end if;

  select * into v_session from public.sessions
  where invite_code = upper(trim(p_code)) and status = 'active';

  if v_session.id is null then
    raise exception 'Código inválido ou sessão não encontrada.';
  end if;

  if v_session.invite_code_expires_at is not null and v_session.invite_code_expires_at < now() then
    raise exception 'Este código expirou. Peça um novo código para quem criou a sessão.';
  end if;

  select count(*) into v_member_count from public.session_members where session_id = v_session.id;
  if v_member_count >= v_session.max_members then
    raise exception 'Esta sessão já está com o número máximo de participantes.';
  end if;

  insert into public.session_members (session_id, user_id, role)
  values (v_session.id, auth.uid(), 'member');

  return v_session;
end;
$$;

create or replace function public.leave_session()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.session_members where user_id = auth.uid();
end;
$$;

create or replace function public.end_session()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session_id uuid;
  v_owner_id uuid;
begin
  select session_id into v_session_id from public.session_members where user_id = auth.uid();
  if v_session_id is null then
    raise exception 'Você não participa de nenhuma sessão.';
  end if;

  select owner_id into v_owner_id from public.sessions where id = v_session_id;
  if v_owner_id <> auth.uid() then
    raise exception 'Apenas quem criou a sessão pode encerrá-la.';
  end if;

  delete from public.session_members where session_id = v_session_id;
  update public.sessions set status = 'ended' where id = v_session_id;
end;
$$;

create or replace function public.regenerate_invite_code()
returns public.sessions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session_id uuid;
  v_session public.sessions;
begin
  select session_id into v_session_id from public.session_members where user_id = auth.uid();
  if v_session_id is null then
    raise exception 'Você não participa de nenhuma sessão.';
  end if;

  update public.sessions
    set invite_code = upper(substr(md5(random()::text || clock_timestamp()::text), 1, 6)),
        invite_code_expires_at = now() + interval '7 days'
    where id = v_session_id
    returning * into v_session;

  return v_session;
end;
$$;

create or replace function public.mark_watched(p_ranking integer, p_title text)
returns public.watched_movies
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session_id uuid;
  v_row public.watched_movies;
begin
  select session_id into v_session_id from public.session_members where user_id = auth.uid();

  if v_session_id is not null then
    insert into public.watched_movies (user_id, session_id, ranking_imdb, nome_filme, assistido, updated_at)
    values (auth.uid(), v_session_id, p_ranking, p_title, true, now())
    on conflict (session_id, ranking_imdb) where session_id is not null
    do update set assistido = true, nome_filme = excluded.nome_filme, user_id = excluded.user_id, updated_at = now()
    returning * into v_row;
  else
    insert into public.watched_movies (user_id, session_id, ranking_imdb, nome_filme, assistido, updated_at)
    values (auth.uid(), null, p_ranking, p_title, true, now())
    on conflict (user_id, ranking_imdb) where session_id is null
    do update set assistido = true, nome_filme = excluded.nome_filme, updated_at = now()
    returning * into v_row;
  end if;

  return v_row;
end;
$$;

create or replace function public.get_watched_ranks()
returns setof integer
language plpgsql
security definer
stable
set search_path = public
as $$
declare
  v_session_id uuid;
begin
  select session_id into v_session_id from public.session_members where user_id = auth.uid();

  if v_session_id is not null then
    return query
      select ranking_imdb from public.watched_movies
      where session_id = v_session_id and assistido = true;
  else
    return query
      select ranking_imdb from public.watched_movies
      where session_id is null and user_id = auth.uid() and assistido = true;
  end if;
end;
$$;

create or replace function public.reset_watched_history()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session_id uuid;
begin
  select session_id into v_session_id from public.session_members where user_id = auth.uid();

  if v_session_id is not null then
    update public.watched_movies set assistido = false, updated_at = now()
      where session_id = v_session_id and assistido = true;
  else
    update public.watched_movies set assistido = false, updated_at = now()
      where session_id is null and user_id = auth.uid() and assistido = true;
  end if;
end;
$$;

-- ----------------------------------------------------------------------------
-- 9. Grants — só usuários autenticados podem chamar as RPCs
-- ----------------------------------------------------------------------------
grant execute on function public.is_session_member(uuid) to authenticated;
grant execute on function public.create_session(text) to authenticated;
grant execute on function public.join_session_by_code(text) to authenticated;
grant execute on function public.leave_session() to authenticated;
grant execute on function public.end_session() to authenticated;
grant execute on function public.regenerate_invite_code() to authenticated;
grant execute on function public.mark_watched(integer, text) to authenticated;
grant execute on function public.get_watched_ranks() to authenticated;
grant execute on function public.reset_watched_history() to authenticated;

-- ----------------------------------------------------------------------------
-- 10. Realtime — habilita a tabela para o client assinar mudanças ao vivo
-- ----------------------------------------------------------------------------
alter publication supabase_realtime add table public.watched_movies;
alter publication supabase_realtime add table public.session_members;
